# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f25b72a846bbdd48a3c82c892dc8e7246479b938f783dcf4eb23f5cd30af5986cf8153ed775279d36a65a1debaf233429810bc914d9c6a0ef636cae6b089eb1

test:
  secret_key_base: c61555955e523ad727e745eb7fd743f99b850086b756d0cd4f6a89f50f068c1159045a79ab8c5fefed77c7c8a817726aecb7a1833084338320d1eb7383aa98b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
